#!/bin/sh

# This script updates the python-sdk and the vision-service-examples repo before
# re-running the scripts in vision-service-examples/canaries. It's designed to be 
# run periodically as a cron job.

# PASSWORD should be passed as env variable
if [ -z "$PASSWORD" ]; then
  echo "please provide root password"
  exit 1
fi

# UPDATE RDK
curl http://packages.viam.com/apps/viam-server/viam-server-latest-aarch64.AppImage -o viam-server
chmod 755 viam-server
echo $PASSWORD | sudo -S ./viam-server --aix-install

VSE="vision-service-examples"
# UPDATE PYTHON SDK
echo "updating viam-sdk and $VSE"
VIAM_SDK=$(pip list --outdated --format=freeze | awk '{split($0, a, "=="); print a[1]}' | grep "viam-sdk")
if [ -n "$VIAM_SDK" ]; then
        pip install --upgrade --no-deps --force-reinstall viam-sdk
        echo "viam-sdk updated"
else
        echo "viam-sdk up-to-date"
fi

# CLONE VIAMROBOTICS/VISION-SERVICE-EXAMPLES
CV="$HOME/$VSE"
if [ -d "$CV" ]; then
  echo "$VSE found. Deleting..."
  rm -rf "$CV"
  echo "successfully deleted"
fi

echo "downloading $VSE to $CV..."
git clone https://github.com/viamrobotics/vision-service-examples.git "$CV"
echo "$VSE downloaded"

# TRY TO DISPLAY THE STREAM AT MOST THREE TIMES, RETRYING THE SERVER EACH TIME
attempt=0
until [ "$attempt" -ge 3 ]
do
  echo "restarting the viam-server"
  echo "$PASSWORD" | sudo -S systemctl restart viam-server.service
  sleep 30  # give the server some time to properly shutdown and startup
  echo "viam-server up"

  echo "displaying xterm window..."
  statusfile=$(mktemp)
  DISPLAY=:0 xterm -e "python3 $CV/canaries/2D_image_stream.py; echo \$? > $statusfile"
  status=$(cat "$statusfile")
  rm $statusfile

  if [ "$status" = 0 ]; then
    echo "success"
    exit
  fi

  attempt=$((attempt+1))
done

echo "failure"
exit 1
